[phases.setup]
nixPkgs = ["python311", "gcc", "glib", "zlib"]

[phases.install]
cmds = [
  "pip install flask insightface onnxruntime opencv-python-headless numpy pillow"
]

[start]
cmd = "bash startup.sh"
